[phases.setup]
nixPkgs = ["libpq"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = [
  "cd backend && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn moomeen.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
